apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: blue-app
          image: us-central1-docker.pkg.dev/igneous-access-450718-i5/my-docker-repo/blue-app:latest
          ports:
            - containerPort: 80
