apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  selector:
    app: green-app  #Change here
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
