apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  selector:
    app: blue-app  #Modify to change from blue to green and reverse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
