name: CI/CD Pipeline for GKE

on:
  push:
    branches:
      - main
      - test

env:
  PROJECT_ID: igneous-access-450718-i5
  REGION: us-central1-a
  REPO: my-docker-repo
  CLUSTER: my-gke-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker us-central1-docker.pkg.dev
          gcloud config set project $PROJECT_ID
          gcloud config set compute/zone $REGION
          gcloud container clusters get-credentials $CLUSTER --zone $REGION --project $PROJECT_ID
          rm key.json

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/${GITHUB_REF##*/}-app:latest
          docker build --platform linux/amd64 -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy to GKE
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/${GITHUB_REF##*/}-app:latest
          kubectl set image deployment/${GITHUB_REF##*/}-app ${GITHUB_REF##*/}-app=$IMAGE_TAG --namespace=default
