name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test

env:
  PROJECT_ID: igneous-access-450718-i5
  REGION: us-central1-a
  REPO: my-docker-repo
  CLUSTER: my-gke-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth list
          gcloud config set project $PROJECT_ID
          gcloud config set compute/region us-central1
          gcloud config set compute/zone us-central1-a

      - name: Install Google Cloud SDK & GKE Auth Plugin
        run: |
          export CLOUD_SDK_REPO="cloud-sdk" 
          echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list 
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - 
          sudo apt-get update -q 
          sudo apt-get install -y google-cloud-sdk 
          gcloud components install gke-gcloud-auth-plugin -q
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/${GITHUB_REF##*/}-app:latest
          docker build --platform linux/amd64 -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER --zone $REGION --project $PROJECT_ID
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${GITHUB_REF##*/}-app ${GITHUB_REF##*/}-app=$IMAGE_TAG
