name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - test

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: my-gke-cluster
  GKE_ZONE: us-central1-a
  IMAGE: blue-app
  IMAGE_TAG: latest
  GAR_ZONE: us-central1
  GAR_REPO: my-docker-repo

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${GAR_ZONE}-docker.pkg.dev

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t ${GAR_ZONE}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPO}/${IMAGE}:${IMAGE_TAG} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${GAR_ZONE}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPO}/${IMAGE}:${IMAGE_TAG}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${GITHUB_REF##*/}-app ${GITHUB_REF##*/}-app=${GAR_ZONE}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPO}/${IMAGE}:${IMAGE_TAG}
